name: frontendlearning
recipe: drupal8
config:
  webroot: .
  php: '7.4'
  composer_version: '1.10.1'
  via: apache
  database: mysql:5.7
  drush: ^8
tooling:
  "compile:scss":
    service: node
    cmd: "gulp -f=gulpfile.js"
    description: "Converts scss to css. Ex: lando compile:scss <themes/watchthemes>"
  "npm":
    service: node
    cmd: "npm"
    description: "Runs npm for installing or removing modules. Ex: lando npm <yourcommand>"
services:
  appserver:
    build:
      - composer install
  node:
    type: node:14
    build:
      - "cd /app && npm install && npm install -g gulp-cli"
